# Generated by Django 5.1.6 on 2025-08-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliants', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='reported_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='category',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='title',
        ),
        migrations.AddField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_photos/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='type',
            field=models.CharField(choices=[('road', 'Road Issue'), ('water', 'Water Issue'), ('electricity', 'Electricity Issue'), ('other', 'Other')], default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ComplaintImage',
        ),
    ]
